var currentEvents = [
  "Random electric company kills bugs for some reason.",
  "Mart of Walls starts selling electric bikes.",
  "Tim Adams recieves a $20,000,000 inheritance, tries to spend it all.",
  "10 ways to heal your skin!              Wait... wrong website.",
  "Plauge Inc. identifies new virus.",
  "Was it boredom that killed the cat? Find out here!",
  "\"Last time I punched a wall, my hand broke!\" says local rager",
  "Everday I wake up, then I start to break up.",
  "Woo-ee-oo I look just like buddy holly.",
  "Bull comments on how targets having a \"bull's eye\" is really harmful to bulls.",
  "Jessica comes out as lesbian, everyone supports her, as they should.",
  "Cats are really cute!",
  "June Exclusive! It's pride month! Everyone cheer!",
  "Tom Adams recognized as a crazy person.",
  "\"Punch\"uation is the new puncuation!",
  "*Crash Cymbal Crashes*",
  "I said, \"It's not what you like, it's what you're like as a person\"",
  "Song lyrics are being used as titles?",
  "FireTree Games publishes new game! This one!",
  "You solved the puzzle.",
  "There's lore.",
  "Every message.",
  "Lore.",
  "Look for it.",
  "There is more.",
  "There actually is no lore, so ignore those current events."
];
